language: go

go:
  - 1.12.x

git:
    # for cloning
    depth: false

before_install:
  - go get -u github.com/gin-gonic/gin

script:
  - go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
